# lts-3.9 is the most recent version supported by Nix. See following
# for the currently-supported versions in Nix:
# nix-instantiate --eval -E "with import <nixpkgs> {}; lib.attrNames haskell.packages"
resolver: lts-3.9

packages:
- '.'

extra-deps:
- turtle-1.2.5

flags: {}

extra-package-dbs: []

nix:
  # Don't depend on end-users to have Nix for the moment. If you want to run using Nix,
  # add `--nix` to the command line, e.g., `stack --nix build`.
  enable: false
  packages: [glpk, pcre, zlib]
